### PR TITLE
fix: Fixed broken link of Layer5 Community Welcome Guide

### LINKED ISSUE #30: [Docs] Broken links of Layer5 Community Welcome Guide
**Current State:**
The Current state of [Layer5 Community Welcome Guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit) is that it has been deleted from the google drive.

**Desired State:**
Both the links should be updated with the new link of the guide.

Screenshots:
image
image

---
**Contributor Resources**
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by Viveksati5143**
**Description**
Fixed broken link of Layer5 Community Welcome Guide in README.md

This PR fixes #30
Closes: #30 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by abhijeetgauravm — APPROVED** [review]
LGTM @Viveksati5143  Thanks for the fix!

**Comment by abhijeetgauravm** [comment]
image
@Viveksati5143 can u fix the link in Readme file as well?

**Comment by Viveksati5143** [comment]
> image @Viveksati5143 can u fixed the link in Readme file as well?

Done @abhijeetgauravm

**Review by abhijeetgauravm — APPROVED** [review]
LGTM @Viveksati5143 . Thanks for the quick fix!🚀 and align your commit message with the changes done next time😅✨

**Comment by Viveksati5143** [comment]
> 

Sorry My bad...actually I made that commit from phone I don't know why would I write _Updated youtube link_ instead of  **Fixed broken link of Layer5 Community Welcome Guide in readme**😅

**Comment by abhijeetgauravm** [comment]
> LGTM @Viveksati5143 Thanks for the fix!

@Chadha93

**Review by Chadha93 — APPROVED** [review]

**Comment by Chadha93** [comment]
Thank you gents.

**Comment by Chadha93** [comment]
Another issue to work on broken image @Viveksati5143 
image

**Comment by Viveksati5143** [comment]
> Another issue to work on broken image @Viveksati5143 image

Thanks @Chadha93 I'll do it!!

**Pull request merged**
