### PR TITLE
added 'help wanted sheild'

### PR DESCRIPTION
**Pull request by san-coding**
Signed-off-by: Sandeep Rajakrishnan <sandur43@gmail.com>

**Description**

This PR fixes issue opened in layer5 repo : [LINK TO ISSUE](https://github.com/layer5io/layer5/issues/2193)

- [x]  Add `help wanted` shield showing help wanted count across `org:layer5io org:meshery org:service-mesh-performance org:service-mesh-patterns`
- [x] Edit `contributors` shield to show contributors count across `org:layer5io org:meshery org:service-mesh-performance org:service-mesh-patterns` or  include the count from `layer5io/layer5` and `meshery/meshery` repos
- [x] Add the twitter accounts for `mesheryio` and `smp_spec` in addition to the `layer5` twitter shield.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by san-coding** [comment]
@leecalcote @warunicorn19 
I have opened the PR here, have added `help wanted` shield , will figure out and do the next 2 tasks now 
- After completing the task 1, the readme looks like this

image

**Comment by warunicorn19** [comment]
Alright sounds good. @san-coding

**Comment by san-coding** [comment]
> Alright sounds good. @san-coding 

Thanks, working on the next 2 tasks on this PR

**Comment by warunicorn19** [comment]
@leecalcote who has access to this repo? can't seem to add reviewers.😅

**Comment by san-coding** [comment]
> @leecalcote who has access to this repo? can't seem to add reviewers.😅

what would be the query for `contributors`  @leecalcote @warunicorn19

**Comment by warunicorn19** [comment]
@debo19, i'll let you take this question.

**Comment by san-coding** [comment]
The existing twitter when clicked was redirecting to repo, instead of twitter, fixed that @leecalcote @warunicorn19 , will now add the twitter handle for `mesheryio` and `smp_spec`

**Comment by san-coding** [comment]
Tast 2 done, added all twitter handles @leecalcote @warunicorn19

**Comment by debo19** [comment]
@san-coding can you send a screenshot of the latest updates?

**Comment by san-coding** [comment]
> @san-coding can you send a screenshot of the latest updates?

Sure, now I have added count sheilds for `layer5io/layer5` and `meshery/meshery`

Here is how it looks now

image

@debo19

**Comment by san-coding** [comment]
@leecalcote @warunicorn19 @debo19 are the changes fine ?

**Comment by debo19** [comment]
@san-coding Looks good but it'll be great if we could combine all contributors into one shield called "contributors". Otherwise just let the org with maximum number of contributors be present at the moment under label = "contributors". We'll add the individual contributors in the Organization section.

**Comment by san-coding** [comment]
Yeah how do I write a query to get total contributors ? @debo19 @leecalcote

**Comment by san-coding** [comment]
@debo , where can I find the list of total contributors to all orgs and repos

**Comment by debo19** [comment]
@san-coding For Layer5 here: https://github.com/layer5io/layer5/graphs/contributors . Similarly you can find for the other repos.

**Comment by debo** [comment]
@san-coding always remember to double check who you tag 😉

**Comment by san-coding** [comment]
> @san-coding always remember to double check who you tag 😉

Oops, sorry 😓

**Comment by san-coding** [comment]
> @san-coding For Layer5 here: https://github.com/layer5io/layer5/graphs/contributors . Similarly you can find for the other repos.

umm... unable to figure out a way to convert it into a GitHub custom search query @debo19 @warunicorn19 @leecalcote

**Comment by leecalcote** [comment]
> @leecalcote who has access to this repo? can't seem to add reviewers.😅

@warunicorn19 good catch. This new repo had not been added to the `layer5-contributors` team as having triage permission. Those permissions have been updated now.

**Comment by leecalcote** [comment]
Heads-up: a merge conflict to resolve - https://github.com/layer5io/.github/pull/6/conflicts

**Comment by san-coding** [comment]
> Heads-up: a merge conflict to resolve - https://github.com/layer5io/.github/pull/6/conflicts

Will resolve soon

**Comment by san-coding** [comment]
@leecalcote have resolved merge conflict as per @debo19 's suggestion

> @san-coding Looks good but it'll be great if we could combine all contributors into one shield called "contributors". Otherwise just let the org with maximum number of contributors be present at the moment under label = "contributors". We'll add the individual contributors in the Organization section.

**Comment by san-coding** [comment]
This is how it looks now, @debo19 @leecalcote 
image

**Review by debo19 — APPROVED** [review]
LGTM 🎉 Thanks @san-coding

**Comment by leecalcote** [comment]
Yay! 🎈

**Comment by san-coding** [comment]
> Yay! 🎈

Thanks @leecalcote @warunicorn19 @debo19 , looking forward to more contributions

**Pull request merged**
